version: "3"
services:
  segmentation:
    image: grihabor/cardiac-segmentation:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - "${SUNNYBROOK_DATA_PATH}:/data/sunnybrook"
      - ./cache:/data/cache
    environment:
      - PYTHONPATH=/project/src
